var annotated =
[
    [ "ARCONTROLLER_DICTIONARY_ARG_t", "structARCONTROLLER__DICTIONARY__ARG__t.html", "structARCONTROLLER__DICTIONARY__ARG__t" ],
    [ "ARCONTROLLER_DICTIONARY_COMMANDS_t", "structARCONTROLLER__DICTIONARY__COMMANDS__t.html", "structARCONTROLLER__DICTIONARY__COMMANDS__t" ],
    [ "ARCONTROLLER_DICTIONARY_ELEMENT_t", "structARCONTROLLER__DICTIONARY__ELEMENT__t.html", "structARCONTROLLER__DICTIONARY__ELEMENT__t" ],
    [ "ARCONTROLLER_DICTIONARY_VALUE_t", "unionARCONTROLLER__DICTIONARY__VALUE__t.html", "unionARCONTROLLER__DICTIONARY__VALUE__t" ],
    [ "ARCONTROLLER_Frame_t", "structARCONTROLLER__Frame__t.html", "structARCONTROLLER__Frame__t" ],
    [ "ARCONTROLLER_NETWORK_SendingConfiguration_t", "structARCONTROLLER__NETWORK__SendingConfiguration__t.html", "structARCONTROLLER__NETWORK__SendingConfiguration__t" ]
];